### ISSUE TITLE
link to pkgdown.yml site

### ISSUE THREAD

**Issue by hansvancalster** [SWittouck/tidyamplicons#9]
Love your package!

I suggest to add a link to https://swittouck.github.io/tidyamplicons/ in the About section of the github repo to increase visibility.

**Comment by SWittouck** [comment]
Hi Hans, 

Thanks! And thanks for the suggestion, I added the link. 

Also good to know maybe: tidyamplicons will soon be continued as [tidytacos](https://github.com/LebeerLab/tidytacos), first release is planned for next week. 

Cheers,
Stijn
